image: atlassian/default-image:2

definitions:
  steps:
    - step: &Build-step
        name: Generate PDFs
        image: bmgandre/docker-archlinux-texlive:0.2.0 
        script:
          - source /etc/profile.d/perlbin.sh
          - |
            echo "Building"
            pwd
            mkdir build
            make DESTDIR=build
        artifacts:
          - build/** 
    - step: &Install-step
        name: Install
        script:
          - |
            echo "Moving PDFs to dist folder"
            pwd
            mkdir -v dist
            mv -v build/*.pdf dist
        artifacts:
          - dist/**
    - step: &Bundle-step
        name: Bundle
        script:
          - |
            GIT_TAG=$( git tag --contains )
            BUNDLE_TAG=${GIT_TAG/\+/.}.b${BITBUCKET_BUILD_NUMBER}
            BUNDLE_NAME=resume-${BUNDLE_TAG}.tar.gz
            [[ ! -z $BUNDLE_TAG ]] && (
              echo "Creating Bundle"
              pwd
              cd dist && pwd
              cp -v ../.version VERSION
              sha256sum *.pdf > SHA256SUMS
              tar -cvzf ../${BUNDLE_NAME} *
              cd .. && pwd
            )
        artifacts:
          - dist/**
          - resume-*.tar.gz
    - step: &Bitbucket-upload-step
        name: Bitbucket upload
        script:
          - |
            GIT_TAG=$( git tag --contains )
            BUNDLE_TAG=${GIT_TAG/\+/.}.b${BITBUCKET_BUILD_NUMBER}
            BUNDLE_NAME=resume-${BUNDLE_TAG}.tar.gz
            [[ ! -z $BUNDLE_TAG ]] && (
              echo "Deploy to Bitbucket Downloads"
              ls -l ${BUNDLE_NAME}
              curl -v -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"./${BUNDLE_NAME}"
            )
    - step: &Dropbox-upload-step
        name: Dropbox upload
        script:
          - |
            GIT_TAG=$( git tag --contains )
            BUNDLE_TAG=${GIT_TAG/\+/.}.b${BITBUCKET_BUILD_NUMBER}
            [[ ! -z $BUNDLE_TAG ]] && (
              echo "Deploy to Dropbox"
              cd dist && pwd
              echo ${DROPBOX_AUTH_STRING} | base64 --decode --ignore-garbage > .dropbox_uploader
              curl "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o dropbox_uploader.sh
              chmod +x dropbox_uploader.sh
              ./dropbox_uploader.sh -f .dropbox_uploader list
              ./dropbox_uploader.sh -f .dropbox_uploader delete ${BUNDLE_TAG} || echo "No previous upload found."
              ./dropbox_uploader.sh -f .dropbox_uploader mkdir ${BUNDLE_TAG}
              ./dropbox_uploader.sh -f .dropbox_uploader upload *.pdf SHA256SUMS VERSION ${BUNDLE_TAG}
              cd .. && pwd
            )

pipelines:
  default:
    - step: *Build-step
    - step: *Install-step
  tags:
    '**':
      - step: *Build-step
      - step: *Install-step
      - step: *Bundle-step
      - step: *Bitbucket-upload-step
      - step: *Dropbox-upload-step
